// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://spnnisomayhcaizexrdv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwbm5pc29tYXloY2FpemV4cmR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NDY3NzEsImV4cCI6MjA3NDAyMjc3MX0.HxHGxiEWXO712y6aHmuQs1MnCd3hKdyUog9vTdW6miY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});